### ISSUE TITLE
Idea: Pls update to 1.20.0

### ISSUE THREAD

**Issue by TNT-King** [StackDoubleFlow/NoodleExtensions#11]

**Comment by MeDrioX** [comment]
Yes Please

**Comment by cal117** [comment]
Hi guys,

**Noodle will be updated when CustomJsonData is fixed**

Please refrain from creating issues when modders are **__*working their arses off*__** trying to fix mods for 1.20.0

Thanks :)

**Comment by BeastGB** [comment]
> Hi guys,
> 
> **Noodle will be updated when CustomJsonData is fixed**
> 
> Please refrain from creating issues when modders are ****_working their arses off_**** trying to fix mods for 1.20.0
> 
> Thanks :)

#arses

**Comment by NukeThief** [comment]
> Hi guys,
> 
> **Noodle will be updated when CustomJsonData is fixed**
> 
> Please refrain from creating issues when modders are ****_working their arses off_**** trying to fix mods for 1.20.0
> 
> Thanks :)

And Now it's time to work for 1.21.0
