### ISSUE TITLE
Walls are dim in modcharts (maybe an issue with wall frames?)

### ISSUE THREAD

**Issue by CGray1234** [StackDoubleFlow/NoodleExtensions#19]
Wall frames just disappear

Example: https://streamable.com/c2ipyn

**Comment by Fernthedev** [comment]
Not a bug, this is how basegame handles walls from now on.
The new wall border has always been disabled by NE to stop a bug where walls with really small scale or negative scale cause weirdness and lag.

**Comment by CGray1234** [comment]
Ah okay, thanks for clarifying
