### ISSUE TITLE
Walls have no frames

### ISSUE THREAD

**Issue by Holioptic** [StackDoubleFlow/NoodleExtensions#22]
Any noodle map with walls will make the walls have no frames, only the core. Does not happen for non-noodle maps.

**Comment by Fernthedev** [comment]
Known issue, not going to be fixed. I'll leave the issue open for future reference

**Comment by kruemmelbande** [comment]
Can we know why its not going to be fixed? It seems like a really anoying issue to me

**Comment by Zayne42** [comment]
bro you should fix this it just makes this mod look like trash

**Comment by Zayne42** [comment]
> Known issue, not going to be fixed. I'll leave the issue open for future reference

you should fix it, it makes your mod look terrible. the old wall algorithm looked so much better

**Comment by Zayne42** [comment]
fix pls

**Comment by millieTime** [comment]
Not the best programmer, but what can I do to move this to willfix?

**Comment by CGray1234** [comment]
This already got fixed iirc

**Comment by CGray1234** [comment]
Anytweaks does interfere with that, so make sure that’s off. It works for me on the latest NE verdion so idk ¯\_(ツ)_/¯

**Comment by Fernthedev** [comment]
Resolved by #81
