### ISSUE TITLE
Walls generating in the wrong spots

### ISSUE THREAD

**Issue by CrowSab5** [StackDoubleFlow/NoodleExtensions#23]
When I play Mawntee’s Dadadada Super Mario Remix, when you get to that part in the beginning where you’re on the “mario course”, the course is to the right of you instead of under you, and the goombas that you slice appear early. Midnight Lady also has a similar bug where the “TV” in the beginning is to the right of you instead of in front of you. Analys by Reaxt also has a small generation issue in one short part of the map. Thank you for bringing noodle extensions to Quest and for all the time and work it took, the community appreciates it.

**Comment by Fernthedev** [comment]
As far as I can tell, this bug is from older versions of NE. Update and if the issue persists, reopen this.
