### ISSUE TITLE
Environment object removal doesn't work properly

### ISSUE THREAD

**Issue by JonnyVR1** [StackDoubleFlow/NoodleExtensions#28]
Example map, Porter Robinson - Shelter https://bsaber.com/songs/1ad55/

The equaliser bars on the left and right sides are removed on the PC version, present in Quest. I believe the wanted behaviour here is to have them removed

**Comment by Fernthedev** [comment]
Noodle doesn't remove environment objects.

**Comment by JonnyVR1** [comment]
Apologies, is this chroma? If so would you like me to open a bug on that repo?

**Comment by Fernthedev** [comment]
If it is a bug, it would be in chroma yes. However I'm surprised of its existence.

**Comment by JonnyVR1** [comment]
https://github.com/bsq-ports/Chroma/issues/23
