### ISSUE TITLE
Some maps crash on certain events

### ISSUE THREAD

**Issue by JonnyVR1** [StackDoubleFlow/NoodleExtensions#29]
Example map, Geoxor - Faerie - https://beatsaver.com/maps/130e6

Crash happens just after the intro section

**Comment by Fernthedev** [comment]
Could you provide a log? quest-help can help you get it

**Comment by JonnyVR1** [comment]
With this log I was actually not able to get past the first note - without the log running though I was sometimes able to get through the intro to the first verse, however, this was very variable and would always crash on the first note of the first verse on the occasions I was able to get that far.

[logcat.log](https://github.com/StackDoubleFlow/NoodleExtensions/files/9389256/logcat.log)
