### ISSUE TITLE
Walls are broken

### ISSUE THREAD

**Issue by Zayne42** [StackDoubleFlow/NoodleExtensions#32]
whenever i hit a wall (they look so danm disgusting now), my game crashes. not just the game, but my **_ENTIRE_** quest.

**Comment by Zayne42** [comment]
also please, **PLEASE** fix those walls

**Comment by Fernthedev** [comment]
Mods are not capable of crashing the quest OS. Wall looks are not up for debate in this manner.

**Comment by kruemmelbande** [comment]
> 

I dont believe such a toggle even exists at all. If your map uses noodle, its gonna have broken walls.
