### ISSUE TITLE
walls PLEASE PLEASE FIX

### ISSUE THREAD

**Issue by Zayne42** [StackDoubleFlow/NoodleExtensions#36]
I mean the walls look just disgusting, like I'm going to puke, and so many people are mad at this issue and all you do is add a "not fix" tag.
I mean maybe, just maybe you could MAYBE listen to us, and fix them. It's like Minecraft. Their critical hit texture had 1 extra pixel, and then they aren't fixing it. It looks gross. like these walls. 😭

**Comment by UnoxReverse** [comment]
i totally agree with you
