### ISSUE TITLE
Noodle crashes Beat Saber when AnyTweaks is enabled.

### ISSUE THREAD

**Issue by avatheavali** [StackDoubleFlow/NoodleExtensions#41]
Title.
I went through the process of elimination for this, and yeah. 
My Noodle version is 1.2.4-beta1, my Beat Saber version is 1.24 (Quest), and my AnyTweaks version is 6.0.0.

Thanks!

**Comment by Fernthedev** [comment]
Process of elimination is unreliable 70% of the time when testing mod conflicts. I do not experience this, therefore closing unless there is a log proving it's not an unreliable crash and actually a NE bug.
