### ISSUE TITLE
version?

### ISSUE THREAD

**Issue by skelybrine** [StackDoubleFlow/NoodleExtensions#50]
what beat saber version does this support? i rlly dont wanna have to revert back to 1.17

**Comment by Nitai610** [comment]
1.25.1

**Comment by ThumusLive** [comment]
Will you update the mod for the 1.27.0 ? (for quest)

**Comment by second2falcon** [comment]
> Will you update the mod for the 1.27.0 ? (for quest)

@ThumusLive That is the question. I just got my quest and don't want to have to "loose" the Rock Mixtape.

**Comment by Fernthedev** [comment]
Not really an issue, and certainly not a place to discuss it.

It'll be updated when it's updated, that's all.
