### ISSUE TITLE
Possible bug: Player doesn't move with parent track

### ISSUE THREAD

**Issue by TheZipCreator** [StackDoubleFlow/NoodleExtensions#51]
If you assign a player to a track (let's say `a`) and then assign a parent track to that track (let's call it `b`), then animations on `b` do not affect the player. However, any other objects attached to track `a` *do* do the animation on track `b`. I'm not sure if the PC version also has this behavior (and I only have beat saber on quest since my PC can't do VR) so I'm not sure if this is a bug or just a quirk of NE.

**Comment by Fernthedev** [comment]
This is not a bug, this is how parent tracks work in both Quest and PC. Player tracks are unaffected by parenting.
