### ISSUE TITLE
BS 24.0 Crash

### ISSUE THREAD

**Issue by Logangster69** [StackDoubleFlow/NoodleExtensions#53]
Beatsaber keeps crashing upon enabling this mod. My only concern is that this extension worked before on (Beatsaber) version 24.0 now it doesn't wanna do anything.

Note: I have tried uninstalling and disabling other mods and it won't budge.

**Comment by bongobil** [comment]
i have maps not working. info button says noodle missing. list of mods says noodle 1.4 enabled?

**Comment by Logangster69** [comment]
Ooooh I found the solution on the same day...😅
I downloaded and installed the "Multiplayer Core" and "Multiplayer (BLANK)" 

This for some reason made noodle extentions work again for my version (1.24) but map extentions not work.

P.S. "Multiplayer (BLANK)" is another mod name I just don't remember the whole name

**Comment by BoogieHasFun** [comment]
If it's been resolved already, make sure to close it :D

**Comment by Logangster69** [comment]
Ig technically it's still a bug but sure
