### ISSUE TITLE
Notes in some recent maps are broken on quest standalone v1.28

### ISSUE THREAD

**Issue by link89** [StackDoubleFlow/NoodleExtensions#58]
Notes in this map https://bsaber.com/songs/36625/  and some others maps are not rendered correctly  or even not rendered on quest standalone v1.28. Is there any work around for this issue?

There are other discussions of this issue, you can find some footage in this thread:
https://www.reddit.com/r/beatsaber/comments/177yijk/several_new_maps_broken_on_quest_standalone_but/

**Comment by Fernthedev** [comment]
Resolved in https://github.com/StackDoubleFlow/CustomJSONData/commit/5de2cd2fe4047e346f080cf5b5ce383facfdc973 and https://github.com/StackDoubleFlow/CustomJSONData/commit/e9cb236034214d1f2ee1567d5f034bdd3ad738c5

**Comment by link89** [comment]
@Fernthedev That's great to know. Will we have a new release of CustomJSONData to upgrade?
