### ISSUE TITLE
Quest 3: Modlist sees the Noodle extensions, but the beat saber songs/maps don’t.

### ISSUE THREAD

**Issue by Ole-VD-Berg** [StackDoubleFlow/NoodleExtensions#61]
When looking at installed/activated mods in beatsaber via modlist, NE seems to be activated. But when I download a song the songs says I don’t have NE installed.
even if i only use a song with noodle extensions and no mapping.

**Comment by magmacyt** [comment]
i also have this problem

**Comment by Axolotl879** [comment]
I’m on version 1.28.0 on quest 2 this issue also happened to me and idk how to fix it 😭😢
