### ISSUE TITLE
There is no target option in AssignPlayerToTrack

### ISSUE THREAD

**Issue by Elecast2** [StackDoubleFlow/NoodleExtensions#64]
There is no target option in AssignPlayerToTrack so the whole player gets tracked
refers to: [AssignPlayerToTrack](https://github.com/Aeroluna/Heck/wiki/Animation#assignplayertotrack)

This breaks an unreleased map I am working in that animate the player's sabers (LeftHand and RightHand target), instead the whole player gets tracked and animated

**Comment by Fernthedev** [comment]
[I originally implemented the feature two years ago in PC](https://github.com/Aeroluna/Heck/pull/54), with the hope of porting it to Quest. The delay of its merge and lack of interest for a large period would later decrease my interest in porting it to Quest.

Anyways this isn't really a bug, it's just a side effect of the burnout from my responsibilities outside of Quest and the lack of interest for contributors to pitch in and help along with a mentally exhausting mod. 

I'll probably work on all of this in summer; though that doesn't mean I wouldn't merge any PR that does implement this or other features.

**Comment by Fernthedev** [comment]
Resolved by #73
