### ISSUE TITLE
Bug with Specific Maps

### ISSUE THREAD

**Issue by sushikid** [StackDoubleFlow/NoodleExtensions#8]
Noodle Extensions do the wrong things (such as randomly flying, notes flying from the wrong spot, random NJS speed) 

VIDEO: https://streamable.com/rjnx8x

**Comment by XJSWAG** [comment]
Try resetting your game. If that doesn't work then shut down your quest then turn it back on.

**Comment by Fernthedev** [comment]
Unable to reproduce
