### ISSUE TITLE
Game Crashing on Startup/When playing a song

### ISSUE THREAD

**Issue by tkiepuszew** [StackDoubleFlow/NoodleExtensions#83]
I tried to boot up beat saber when it just turned off, once i got it, i chose a song (that didn't have the requirement for NE) and it crashed
i asked BSMG for why does it happen and turned off the mod and now beat saber works

Crash logs: https://analyzer.questmodding.com/crashes?userId=FakePlayer

**Comment by Fernthedev** [comment]
This crash is not related to NoodleExtensions. Nothing I can do since it's not consistent either.

**Comment by tkiepuszew** [comment]
the fuck you mean, once i disabled NE it stopped crashing

**Comment by tkiepuszew** [comment]
NE is all over the crash logs (Ctrl + F btw and search noodleextensions)
